import { useState, useRef } from 'react';
import {
  ArrowLeft, Calendar, X, Sparkles, Download,
  MapPin, Utensils, Plane, Building2, Lightbulb,
  ChevronRight, Clock, Star, Loader2, CheckCircle,
} from 'lucide-react';
import { searchFlights, searchHotels, type FlightOffer, type HotelOffer } from '../services/mockTravelAPI';
import {
  getDestinationInfo,
  generateTemplatePlan,
  type DestinationInfo,
  type DayTemplate,
} from '../services/mockDestinationAPI';
import { createGLMClientFromEnv } from '../services/glmClient';
import jsPDF from 'jspdf';
import '../styles/TripPlannerPage.css';

// ─── Types ────────────────────────────────────────────────────────────────────

type PageView = 'setup' | 'generating' | 'result';

interface GeneratedPlan {
  destination: string;
  origin: string;
  startDate: string;
  endDate: string;
  numDays: number;
  destInfo: DestinationInfo;
  days: DayTemplate[];
  flight: FlightOffer | null;
  hotel: HotelOffer | null;
  preferences: string[];
  aiNarrative: string | null;
  totalBudgetMYR: number;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

const DESTINATIONS_LIST = ['London', 'Paris', 'Tokyo', 'Sydney', 'Melbourne', 'Bali', 'Bangkok', 'Singapore', 'Seoul', 'Dubai'];

function daysBetween(start: string, end: string): number {
  if (!start || !end) return 5;
  const s = new Date(start);
  const e = new Date(end);
  const diff = Math.round((e.getTime() - s.getTime()) / (1000 * 60 * 60 * 24));
  return Math.max(1, diff);
}

function formatDate(dateStr: string): string {
  if (!dateStr) return '';
  const d = new Date(dateStr);
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
}

function addDays(dateStr: string, days: number): string {
  if (!dateStr) return '';
  const d = new Date(dateStr);
  d.setDate(d.getDate() + days);
  return d.toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'short' });
}

function getAccomLevel(prefs: string[]): 'budget' | 'comfort' | 'luxury' {
  if (prefs.includes('Luxury'))  return 'luxury';
  if (prefs.includes('Premium')) return 'comfort';
  return 'budget';
}

/**
 * jsPDF standard fonts (Helvetica) only support WinAnsi. Emoji, arrows, fancy dashes,
 * and star symbols become mojibake unless we normalize or strip them.
 */
function sanitizePdfText(s: string): string {
  return s
    .replace(/[\u2190-\u2199\u21A6\u27A1\u2794]/g, '->')
    .replace(/[\u2010-\u2015\u2212]/g, '-')
    .replace(/[\u2022\u2023\u2043\u2219\u25E6]/g, '-')
    .replace(/[\u2605\u2606\u272F\u2730]/g, '*')
    .replace(/\uFE0F/g, '')
    .replace(/\p{Extended_Pictographic}/gu, '');
}

function starsPdf(n: number): string {
  return n > 0 ? `${'*'.repeat(Math.min(n, 5))} (${n} star${n === 1 ? '' : 's'})` : '';
}

// ─── PDF Generator ────────────────────────────────────────────────────────────

function exportToPDF(plan: GeneratedPlan) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = 210;
  const margin = 15;
  let y = margin;

  const purple = [123, 44, 191] as [number, number, number];
  const blue   = [68, 97, 242]  as [number, number, number];

  const checkY = (needed: number) => {
    if (y + needed > 280) { doc.addPage(); y = margin; }
  };

  doc.setFillColor(...purple);
  doc.rect(0, 0, W, 45, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(sanitizePdfText(`${plan.destination} Trip Itinerary`), margin, 20);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(
    sanitizePdfText(
      `${plan.origin} -> ${plan.destination} | ${formatDate(plan.startDate)} - ${formatDate(plan.endDate)} | ${plan.numDays} Days`,
    ),
    margin,
    32,
  );
  doc.text(sanitizePdfText(`Generated by ZenTravel AI | ${new Date().toLocaleDateString()}`), margin, 40);
  y = 55;

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('TRAVEL ESSENTIALS', margin, y);
  y += 7;
  doc.setDrawColor(...purple);
  doc.line(margin, y, W - margin, y);
  y += 7;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  if (plan.flight) {
    doc.setFont('helvetica', 'bold');
    doc.text('Recommended Flight', margin, y);
    doc.setFont('helvetica', 'normal');
    doc.text(
      sanitizePdfText(
        `${plan.flight.airline} ${plan.flight.flightNumber} - ${plan.flight.cabin} - MYR ${plan.flight.priceMYR.toLocaleString()}`,
      ),
      margin + 5,
      y + 6,
    );
    y += 15;
  }
  if (plan.hotel) {
    doc.setFont('helvetica', 'bold');
    doc.text('Recommended Hotel', margin, y);
    doc.setFont('helvetica', 'normal');
    doc.text(
      sanitizePdfText(
        `${plan.hotel.name} - ${starsPdf(plan.hotel.stars)} - MYR ${plan.hotel.priceMYR}/night - ${plan.hotel.distance}`,
      ),
      margin + 5,
      y + 6,
    );
    y += 15;
  }

  const budgetLevel = getAccomLevel(plan.preferences);
  const daily = plan.destInfo.avgDailyBudgetMYR[budgetLevel];
  doc.setFont('helvetica', 'bold');
  doc.text('Estimated Budget', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(
    sanitizePdfText(
      `~MYR ${(daily * plan.numDays + (plan.flight?.priceMYR ?? 0)).toLocaleString()} total (MYR ${daily}/day x ${plan.numDays} days + flights)`,
    ),
    margin + 5,
    y + 6,
  );
  y += 18;

  for (const day of plan.days) {
    checkY(55);
    doc.setFillColor(...blue);
    doc.rect(margin, y, W - margin * 2, 10, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(
      sanitizePdfText(
        `  DAY ${day.dayNumber} - ${day.theme.toUpperCase()} (${addDays(plan.startDate, day.dayNumber - 1)})`,
      ),
      margin + 2,
      y + 7,
    );
    y += 14;
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');

    const activities = [
      day.morningActivity   && { time: 'Morning',   act: day.morningActivity },
      day.afternoonActivity && { time: 'Afternoon', act: day.afternoonActivity },
      day.eveningActivity   && { time: 'Evening',   act: day.eveningActivity },
    ].filter(Boolean) as { time: string; act: NonNullable<DayTemplate['morningActivity']> }[];

    for (const { time, act } of activities) {
      checkY(18);
      doc.setFont('helvetica', 'bold');
      doc.text(sanitizePdfText(`${time}: ${act.name}`), margin + 3, y);
      doc.setFont('helvetica', 'normal');
      const lines = doc.splitTextToSize(sanitizePdfText(act.description), W - margin * 2 - 8);
      doc.text(lines, margin + 5, y + 5);
      if (act.entryFee) doc.text(sanitizePdfText(`Entry: ${act.entryFee}`), margin + 5, y + 5 + lines.length * 4 + 1);
      y += 5 + lines.length * 4 + (act.entryFee ? 5 : 2) + 2;
    }

    checkY(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Must-Try Today', margin + 3, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    const meals = [
      `Breakfast: ${day.meals.breakfast.name} @ ${day.meals.breakfast.where}`,
      `Lunch: ${day.meals.lunch.name} @ ${day.meals.lunch.where}`,
      `Dinner: ${day.meals.dinner.name} @ ${day.meals.dinner.where}`,
    ];
    for (const m of meals) {
      checkY(6);
      doc.text(sanitizePdfText(`  - ${m}`), margin + 3, y);
      y += 5;
    }

    checkY(10);
    doc.setTextColor(...purple);
    doc.setFont('helvetica', 'italic');
    doc.text(sanitizePdfText(`Tip: ${day.tip}`), margin + 3, y + 2);
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'normal');
    y += 10;
  }

  doc.addPage();
  doc.setFillColor(...purple);
  doc.rect(0, 0, W, 30, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('General Travel Tips', margin, 18);
  y = 40;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  for (const tip of plan.destInfo.tips) {
    checkY(10);
    const lines = doc.splitTextToSize(sanitizePdfText(`- ${tip}`), W - margin * 2);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 3;
  }

  doc.save(`ZenTravel_${plan.destination}_${plan.startDate || 'Trip'}.pdf`);
}

// ─── Main Component ───────────────────────────────────────────────────────────

export const TripPlannerPage = ({ setView }: { setView: (v: string) => void }) => {
  const [origin,      setOrigin]      = useState('Kuala Lumpur');
  const [destination, setDestination] = useState('London');
  const [customDest,  setCustomDest]  = useState('');
  const [startDate,   setStartDate]   = useState('');
  const [endDate,     setEndDate]     = useState('');
  const [selectedPrefs, setSelectedPrefs] = useState<string[]>([]);
  const [otherNeeds,    setOtherNeeds]    = useState('');

  const [showDateModal, setShowDateModal] = useState(false);
  const [showPrefModal, setShowPrefModal] = useState(false);

  const [pageView,    setPageView]    = useState<PageView>('setup');
  const [genStatus,   setGenStatus]   = useState('');
  const [plan,        setPlan]        = useState<GeneratedPlan | null>(null);
  const [expandedDay, setExpandedDay] = useState<number | null>(null);

  const planRef = useRef<HTMLDivElement>(null);

  const prefCategories = [
    { label: 'Travel companions', items: ['🚶 Solo', '👪 Family', '💑 Couple', '👬 Friends', '👵 Elderly'] },
    { label: 'Travel style',      items: ['🚩 Cultural', '🌟 Classic', '🍃 Nature', '🌇 Cityscape', '🏛️ Historical'] },
    { label: 'Travel pace',       items: ['📅 Ambitious', '🕒 Moderate', '🌴 Relaxed'] },
    { label: 'Accommodation',     items: ['Comfort', 'Premium', 'Luxury'] },
    { label: "Day's rhythm",      items: ['🐦 Early starts', '🦉 Late nights'] },
  ];

  const togglePref = (item: string) =>
    setSelectedPrefs(prev => prev.includes(item) ? prev.filter(i => i !== item) : [...prev, item]);

  const effectiveDest = customDest.trim() || destination;

  // ─── AI Trip Generation ─────────────────────────────────────────────────────

  const handleAIPlan = async () => {
    setPageView('generating');
    setGenStatus('Searching for best flights…');

    try {
      const [flights, hotels, destInfo] = await Promise.all([
        searchFlights(origin, effectiveDest, 'Economy'),
        searchHotels(effectiveDest),
        getDestinationInfo(effectiveDest),
      ]);

      setGenStatus('Curating top attractions & experiences…');
      const numDays = daysBetween(startDate, endDate);
      const days    = generateTemplatePlan(destInfo, numDays, selectedPrefs);

      setGenStatus('Asking AI to craft your personalised narrative…');
      let aiNarrative: string | null = null;
      const glm = createGLMClientFromEnv();
      if (glm) {
        try {
          const prefsText = selectedPrefs.join(', ') || 'general traveller';
          const prompt = `You are ZenTravel AI. Generate a SHORT, warm, encouraging 3-sentence travel intro for a ${numDays}-day trip from ${origin} to ${destInfo.city}, ${destInfo.country}. Traveller preferences: ${prefsText}. ${otherNeeds ? 'Special needs: ' + otherNeeds + '.' : ''} Best season: ${destInfo.bestSeason}. Mention 1–2 must-see highlights from: ${destInfo.attractions.slice(0, 3).map(a => a.name).join(', ')}. Keep it under 80 words. Enthusiastic, personal tone.`;
          aiNarrative = await glm.complete([{ role: 'user', content: prompt }], 200);
        } catch {
          // Fall back to template narrative
        }
      }

      setGenStatus('Building your personalised itinerary…');
      await new Promise(r => setTimeout(r, 600));

      const topFlight = flights.find(f => f.recommended) ?? flights[0] ?? null;
      const accomLevel = getAccomLevel(selectedPrefs);
      const topHotel  = hotels.find(h =>
        accomLevel === 'luxury'  ? h.stars >= 4 :
        accomLevel === 'comfort' ? h.stars >= 3 : true
      ) ?? hotels[0] ?? null;

      const flightCost  = topFlight?.priceMYR ?? 0;
      const hotelCost   = (topHotel?.priceMYR ?? 0) * numDays;
      const daily       = destInfo.avgDailyBudgetMYR[accomLevel];
      const totalBudget = flightCost + hotelCost + daily * numDays;

      setPlan({
        destination: destInfo.city,
        origin,
        startDate,
        endDate,
        numDays,
        destInfo,
        days,
        flight: topFlight,
        hotel: topHotel,
        preferences: selectedPrefs,
        aiNarrative,
        totalBudgetMYR: totalBudget,
      });

      setPageView('result');
      setExpandedDay(1);
    } catch (err) {
      console.error(err);
      setGenStatus('Something went wrong. Please try again.');
      setTimeout(() => setPageView('setup'), 2000);
    }
  };

  // ─── Render: Setup ──────────────────────────────────────────────────────────

  if (pageView === 'setup') {
    return (
      <div className="tp-page fade-in">
        <header className="tp-header">
          <button className="tp-back-btn" onClick={() => setView('home')}>
            <ArrowLeft size={20} />
          </button>
          <span className="tp-header-title">Trip Planner</span>
          <div className="tp-header-spacer" />
        </header>

        <main className="tp-main">
          {/* ── Setup Card ── */}
          <div className="tp-setup-card">

            {/* Origin */}
            <div className="tp-row">
              <span className="tp-row-label">Starting from</span>
              <input
                className="tp-origin-input"
                value={origin}
                onChange={e => setOrigin(e.target.value)}
                placeholder="City or airport"
              />
            </div>

            <div className="tp-divider" />

            {/* Destination */}
            <div className="tp-dest-section">
              <div className="tp-row tp-row-no-border">
                <span className="tp-row-label">Heading To</span>
                <ChevronRight size={16} color="#9b72cf" />
              </div>
              <div className="tp-dest-scroll">
                {DESTINATIONS_LIST.map(d => (
                  <div
                    key={d}
                    className={`tp-dest-pill ${destination === d && !customDest ? 'tp-dest-pill--selected' : ''}`}
                    onClick={() => { setDestination(d); setCustomDest(''); }}
                  >
                    {d}
                  </div>
                ))}
              </div>
              <div className="tp-custom-dest-wrap">
                <input
                  className="tp-custom-dest-input"
                  value={customDest}
                  onChange={e => setCustomDest(e.target.value)}
                  placeholder="Or type another destination…"
                />
              </div>
            </div>

            <div className="tp-divider" />

            {/* Dates */}
            <div className="tp-row tp-row-clickable" onClick={() => setShowDateModal(true)}>
              <div className="tp-row-left">
                <Calendar size={18} color="#9b72cf" />
                <span className="tp-row-value">
                  {startDate && endDate
                    ? `${formatDate(startDate)} → ${formatDate(endDate)} (${daysBetween(startDate, endDate)} days)`
                    : 'Select travel dates'}
                </span>
              </div>
              <ChevronRight size={16} color="#9b72cf" />
            </div>

            <div className="tp-divider" />

            {/* Preferences */}
            <div className="tp-row tp-row-clickable" onClick={() => setShowPrefModal(true)}>
              <div className="tp-pref-trigger">
                <span className="tp-row-label">Preferences</span>
                {selectedPrefs.length > 0 && (
                  <span className="tp-prefs-preview">
                    {selectedPrefs.slice(0, 3).join(' · ')}{selectedPrefs.length > 3 ? ' …' : ''}
                  </span>
                )}
              </div>
              <ChevronRight size={16} color="#9b72cf" />
            </div>
          </div>

          {/* ── Action Buttons ── */}
          <div className="tp-actions">
            <button className="tp-ai-btn" onClick={handleAIPlan}>
              <Sparkles size={18} /> Plan a Trip with AI
            </button>
            <button className="tp-manual-btn" onClick={() => setView('manual-planner')}>
              Create It Myself
            </button>
          </div>
        </main>

        {/* Preferences Modal */}
        {showPrefModal && (
          <div className="tp-modal-overlay" onClick={() => setShowPrefModal(false)}>
            <div className="tp-modal-card tp-pref-modal" onClick={e => e.stopPropagation()}>
              <button className="tp-modal-close" onClick={() => setShowPrefModal(false)}>
                <X size={18} />
              </button>
              <h3 className="tp-modal-title">Your Preferences</h3>
              <div className="tp-pref-scroll">
                {prefCategories.map(cat => (
                  <div key={cat.label} className="tp-pref-group">
                    <span className="tp-pref-group-label">{cat.label}</span>
                    <div className="tp-chips">
                      {cat.items.map(item => (
                        <div
                          key={item}
                          className={`tp-chip ${selectedPrefs.includes(item) ? 'tp-chip--active' : ''}`}
                          onClick={() => togglePref(item)}
                        >
                          {item}
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
                <span className="tp-pref-group-label">Other needs</span>
                <textarea
                  className="tp-other-needs"
                  placeholder="Dietary requirements, mobility needs, special occasions…"
                  value={otherNeeds}
                  onChange={e => setOtherNeeds(e.target.value)}
                  rows={3}
                />
              </div>
              <button className="tp-confirm-btn" onClick={() => setShowPrefModal(false)}>
                Done
              </button>
            </div>
          </div>
        )}

        {/* Date Modal */}
        {showDateModal && (
          <div className="tp-modal-overlay" onClick={() => setShowDateModal(false)}>
            <div className="tp-modal-card tp-date-modal" onClick={e => e.stopPropagation()}>
              <button className="tp-modal-close" onClick={() => setShowDateModal(false)}>
                <X size={18} />
              </button>
              <h3 className="tp-modal-title">Select Travel Dates</h3>
              <div className="tp-date-inputs">
                <div className="tp-date-field">
                  <label className="tp-date-label">Departure</label>
                  <input
                    type="date"
                    className="tp-date-input"
                    value={startDate}
                    onChange={e => setStartDate(e.target.value)}
                    min={new Date().toISOString().split('T')[0]}
                  />
                </div>
                <div className="tp-date-field">
                  <label className="tp-date-label">Return</label>
                  <input
                    type="date"
                    className="tp-date-input"
                    value={endDate}
                    onChange={e => setEndDate(e.target.value)}
                    min={startDate || new Date().toISOString().split('T')[0]}
                  />
                </div>
                {startDate && endDate && (
                  <div className="tp-duration-badge">
                    ✈ {daysBetween(startDate, endDate)}-day trip
                  </div>
                )}
              </div>
              <button className="tp-confirm-btn" onClick={() => setShowDateModal(false)}>
                Confirm Dates
              </button>
            </div>
          </div>
        )}

      </div>
    );
  }

  // ─── Render: Generating ─────────────────────────────────────────────────────

  if (pageView === 'generating') {
    const GEN_STEPS = [
      'Searching for best flights…',
      'Curating top attractions & experiences…',
      'Asking AI to craft your personalised narrative…',
      'Building your personalised itinerary…',
    ];
    const currentIdx = GEN_STEPS.indexOf(genStatus);

    return (
      <div className="tp-page fade-in">
        <header className="tp-header">
          <button className="tp-back-btn" onClick={() => setPageView('setup')}>
            <ArrowLeft size={20} />
          </button>
          <span className="tp-header-title">Planning Your Trip</span>
          <div className="tp-header-spacer" />
        </header>
        <div className="tp-generating">
          <div className="tp-gen-plane">✈️</div>
          <h2 className="tp-gen-title">Crafting your perfect trip…</h2>
          <p className="tp-gen-route">{origin} → {effectiveDest}</p>
          <div className="tp-gen-steps">
            {GEN_STEPS.map((step, i) => {
              const done   = i < currentIdx;
              const active = i === currentIdx;
              return (
                <div key={step} className={`tp-gen-step ${done ? 'tp-gen-step--done' : active ? 'tp-gen-step--active' : 'tp-gen-step--pending'}`}>
                  {done   ? <CheckCircle size={18} color="#28C76F" /> :
                   active ? <Loader2    size={18} color="#7b2cbf" className="tp-spin" /> :
                            <span className="tp-gen-dot" />}
                  <span>{step}</span>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    );
  }

  // ─── Render: Result ─────────────────────────────────────────────────────────

  if (!plan) return null;

  return (
    <div className="tp-page fade-in">
      <header className="tp-header">
        <button className="tp-back-btn" onClick={() => setPageView('setup')}>
          <ArrowLeft size={20} />
        </button>
        <span className="tp-header-title">{plan.destination} Itinerary</span>
        <div className="tp-header-spacer" />
      </header>

      <main className="tp-result-main" ref={planRef}>

        {/* ── Hero ── */}
        <div className="tp-hero">
          <div className="tp-hero-emoji">{plan.destInfo.emoji}</div>
          <div className="tp-hero-info">
            <h2 className="tp-hero-title">{plan.destination}</h2>
            <p className="tp-hero-sub">{plan.origin} · {plan.numDays} Days · {formatDate(plan.startDate)} – {formatDate(plan.endDate)}</p>
            {plan.preferences.length > 0 && (
              <div className="tp-hero-prefs">
                {plan.preferences.slice(0, 4).map(p => (
                  <span key={p} className="tp-pref-badge">{p}</span>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* ── AI Narrative ── */}
        {plan.aiNarrative && (
          <div className="tp-narrative">
            <Sparkles size={15} color="#7b2cbf" style={{ flexShrink: 0, marginTop: 2 }} />
            <p className="tp-narrative-text">{plan.aiNarrative}</p>
          </div>
        )}

        {/* ── Essentials Grid ── */}
        <div className="tp-essentials-grid">
          {plan.flight && (
            <div className="tp-essential-card">
              <div className="tp-essential-icon" style={{ background: '#E8EDFF' }}>
                <Plane size={18} color="#4461F2" />
              </div>
              <div className="tp-essential-label">Best Flight</div>
              <div className="tp-essential-value">{plan.flight.airline}</div>
              <div className="tp-essential-sub">{plan.flight.flightNumber} · {plan.flight.cabin}</div>
              <div className="tp-essential-price">MYR {plan.flight.priceMYR.toLocaleString()}</div>
            </div>
          )}
          {plan.hotel && (
            <div className="tp-essential-card">
              <div className="tp-essential-icon" style={{ background: '#F3EBFF' }}>
                <Building2 size={18} color="#7b2cbf" />
              </div>
              <div className="tp-essential-label">Recommended Stay</div>
              <div className="tp-essential-value">{plan.hotel.name}</div>
              <div className="tp-essential-sub">{'★'.repeat(plan.hotel.stars)} · {plan.hotel.distance}</div>
              <div className="tp-essential-price">MYR {plan.hotel.priceMYR.toLocaleString()}/night</div>
            </div>
          )}
        </div>

        {/* ── Budget ── */}
        <div className="tp-budget-card">
          <Star size={15} color="#FF9F43" fill="#FF9F43" />
          <div className="tp-budget-info">
            <span className="tp-budget-label">Estimated Total Budget</span>
            <span className="tp-budget-value">MYR {plan.totalBudgetMYR.toLocaleString()}</span>
          </div>
          <span className="tp-budget-note">incl. flights, hotel & daily expenses</span>
        </div>

        {/* ── Day-by-Day ── */}
        <div className="tp-section-header">
          <span className="tp-section-label">📅 Your {plan.numDays}-Day Itinerary</span>
        </div>

        {plan.days.map((day) => (
          <div key={day.dayNumber} className="tp-accordion">
            <button
              className={`tp-accordion-header ${expandedDay === day.dayNumber ? 'tp-accordion-header--open' : ''}`}
              onClick={() => setExpandedDay(expandedDay === day.dayNumber ? null : day.dayNumber)}
            >
              <div className="tp-accordion-left">
                <span className="tp-day-badge">Day {day.dayNumber}</span>
                <div>
                  <div className="tp-day-theme">{day.theme}</div>
                  <div className="tp-day-date">{addDays(plan.startDate, day.dayNumber - 1)}</div>
                </div>
              </div>
              <ChevronRight
                size={17}
                color="#9b72cf"
                style={{ transform: expandedDay === day.dayNumber ? 'rotate(90deg)' : 'none', transition: 'transform 0.2s' }}
              />
            </button>

            {expandedDay === day.dayNumber && (
              <div className="tp-accordion-body">
                {[
                  { time: 'Morning',   Icon: Clock,  act: day.morningActivity },
                  { time: 'Afternoon', Icon: MapPin,  act: day.afternoonActivity },
                  { time: 'Evening',   Icon: Star,    act: day.eveningActivity },
                ].filter(s => s.act).map(({ time, Icon, act }) => act && (
                  <div key={time} className="tp-activity">
                    <div className="tp-activity-time">
                      <Icon size={12} /> {time}
                    </div>
                    <div className="tp-activity-name">{act.name}</div>
                    <div className="tp-activity-desc">{act.description}</div>
                    <div className="tp-activity-meta">
                      <span>⏱ {act.duration}</span>
                      {act.entryFee && <span>🎟 {act.entryFee}</span>}
                      <span>📍 {act.neighborhood}</span>
                    </div>
                  </div>
                ))}

                {/* Meals */}
                <div className="tp-meals">
                  <div className="tp-meals-header">
                    <Utensils size={13} color="#FF9F43" /> Must-Try Food Today
                  </div>
                  {[
                    { label: '🌅 Breakfast', food: day.meals.breakfast },
                    { label: '☀️ Lunch',     food: day.meals.lunch },
                    { label: '🌙 Dinner',    food: day.meals.dinner },
                  ].map(({ label, food }) => (
                    <div key={label} className="tp-meal-row">
                      <span className="tp-meal-label">{label}</span>
                      <div>
                        <div className="tp-meal-name">{food.name}</div>
                        <div className="tp-meal-meta">{food.where} · {food.priceMYR}</div>
                      </div>
                    </div>
                  ))}
                </div>

                {/* Tip */}
                <div className="tp-tip">
                  <Lightbulb size={13} color="#7b2cbf" style={{ flexShrink: 0, marginTop: 2 }} />
                  <span>{day.tip}</span>
                </div>
              </div>
            )}
          </div>
        ))}

        {/* ── Essential Tips ── */}
        <div className="tp-section-header">
          <span className="tp-section-label">💡 Essential Tips for {plan.destination}</span>
        </div>
        <div className="tp-tips-card">
          {plan.destInfo.tips.map((tip, i) => (
            <div key={i} className="tp-tip-row">
              <CheckCircle size={14} color="#28C76F" style={{ flexShrink: 0 }} />
              <span>{tip}</span>
            </div>
          ))}
          <div className="tp-tip-row">
            <CheckCircle size={14} color="#28C76F" style={{ flexShrink: 0 }} />
            <span>Best time to visit: {plan.destInfo.bestSeason}</span>
          </div>
          <div className="tp-tip-row">
            <CheckCircle size={14} color="#28C76F" style={{ flexShrink: 0 }} />
            <span>Local currency: {plan.destInfo.currency}</span>
          </div>
        </div>

        {/* ── Must-Try Foods ── */}
        <div className="tp-section-header">
          <span className="tp-section-label">🍽 All Must-Try Foods</span>
        </div>
        <div className="tp-foods-grid">
          {plan.destInfo.foods.map((food, i) => (
            <div key={i} className="tp-food-card">
              <div className="tp-food-name">{food.name}</div>
              <div className="tp-food-desc">{food.description}</div>
              <div className="tp-food-meta">{food.where} · {food.priceMYR}</div>
            </div>
          ))}
        </div>

        {/* ── Export ── */}
        <div className="tp-export-row">
          <button className="tp-ai-btn" onClick={() => exportToPDF(plan)}>
            <Download size={17} /> Export as PDF
          </button>
          <button className="tp-manual-btn" onClick={() => setView('manual-planner')}>
            Customise Manually
          </button>
        </div>
      </main>

    </div>
  );
};
